### ISSUE TITLE
SCRIPT_VERSION out of sync with release version

### ISSUE THREAD

**Issue by daftmugi** [NamelessVoice/NVScript#3]
When inspecting the version info of the OSM, it is out of sync with `SCRIPT_VERSION` in the code.

For example, release `1.3.0` has the following version info:
```
Comment = FileVersion: 1.2.8.0
FileVersion: 1.2.8
ProductVersion: 1.2.8.0
```
And, game log output:
```
Loaded script module "nvscript.osm" [FileVer=1.2.8.0 ; ProductVer=1.2.8.0 ; FileModDate=2022-Nov-07]
```

**Comment by NamelessVoice** [comment]
Must have forgotten to update the version file.

Fixed now.

**Comment by daftmugi** [comment]
Out of sync version again: `1.3.1` displays as `1.3.0`.

**Comment by NamelessVoice** [comment]
Fixed again.

And updated the code so the version number is no longer kept in two places, to avoid it happening again.
