### ISSUE TITLE
Random Disabling the intelligence of servants in Thief Gold

### ISSUE THREAD

**Issue by Sergiut99** [NamelessVoice/NVScript#4]
![dump002](https://user-images.githubusercontent.com/100404282/221402020-468f1894-6f8d-4bd4-8f05-ecaf6ab92d49.png)
I noticed this Issue on the first map. Jump into the well. Swim through the sewers... Enter the castle... go up the stairs... you will see the servants' quarters. in one room, a servant sleeps on a bed... Wake him up... He'll get up... In some cases, he cannot escape from the player...He says he hears a noise, but he can't run... Sometimes he runs away.. This is a random Issue. please  fix it.

**Comment by NamelessVoice** [comment]
Uhh...  what does that have to do with NVScript?

**Comment by Sergiut99** [comment]
> 

This is issue of TFix 1.27?

**Comment by NamelessVoice** [comment]
This is the repository and issue tracker for NVScript - a script module mostly used by FMs.  It's not related to TFix in any way.

If you want to report issues with TFix, send them to Voodoo47 on TTLG.
