### ISSUE TITLE
Windows XP compatibility

### ISSUE THREAD

**Issue by adelpha** [NamelessVoice/NVScript#6]
I realise this is probably very low on your list of priorities - I can't imagine many people are still running this on a dead OS - but XP support seems to have been broken after 1.2.9. Versions 1.3.0 and 1.3.1 fail to load with an Error 127 generated in the logs.

I only mention this at all because when you run SS2Tool on XP it tells you to run it on a Vista or higher machine and then copy the install across to an XP machine, but this doesn't work because it installs a later version of NVScript.osm that no longer loads on XP.

I've only tested with System Shock 2.

**Comment by NamelessVoice** [comment]
These builds should (theoretically) work on Windows XP.
But I'm unsure if I can finagle the GitHub-based builds to actually use this no-longer-supported toolset.

[NVScript-SS2-XP.zip](https://github.com/user-attachments/files/16420106/NVScript-SS2-XP.zip)
[NVScript-T1-XP.zip](https://github.com/user-attachments/files/16420107/NVScript-T1-XP.zip)
[NVScript-T2-XP.zip](https://github.com/user-attachments/files/16420108/NVScript-T2-XP.zip)

**Comment by adelpha** [comment]
Awesome, thanks. Yep that build works perfectly. Thanks for the really quick response!

**Comment by NamelessVoice** [comment]
New builds will now be compatible with Windows XP.
